/* ============================================================
   Exploratory Data Analysis (EDA)
   Dataset : Sakila Database
   Purpose : Analyze film rentals, customer behavior,
             revenue generation, and store performance
   ============================================================ */

   -- 2. Descriptive statistics for film lengt
SELECT 
    MAX(length) AS max_length,
    MIN(length) AS min_length,
    AVG(length) AS avg_length
FROM film_tab;

    -- 3. Distribution of films by rating
SELECT 
    rating, COUNT(*) AS rating_film
FROM film_tab
WHERE rating IS NOT NULL
GROUP BY rating
ORDER BY rating_film DESC;

  -- 4. Number of films per category
SELECT c.name AS category, COUNT(*) AS count_film
FROM film f
JOIN film_category fc ON f.film_id = fc.film_id
JOIN category c ON fc.category_id = c.category_id
GROUP BY c.name
ORDER BY count_film desc;

/* -- 5. Rental frequency for a specific film
      (using Common Table Expression)*/
WITH tab AS (
    SELECT f.title, COUNT(r.rental_id) AS count_rental_id
    FROM rental_tab r
    JOIN inventory i ON i.inventory_id = r.inventory_id
    JOIN film f ON f.film_id = i.film_id
    GROUP BY f.title
    ORDER BY count_rental_id DESC
)
SELECT * FROM tab
WHERE title = 'Blanket Beverly';

    -- 6. Total number of customers
SELECT COUNT(*)
FROM customer_tab;

  -- 7. Active vs inactive customers
SELECT active, COUNT(*) AS customer_count
FROM customer_tab
GROUP BY active
ORDER BY customer_count DESC;

  -- 8. Customer distribution by city
SELECT c.city,COUNT(*) AS customer_count
FROM city_tab c
JOIN address_tab a ON c.city_id = a.city_id
JOIN customer_tab t ON t.address_id = a.address_id
GROUP BY c.city
ORDER BY customer_count DESC;

  -- 9. Total number of staff members
SELECT COUNT(*)
FROM staff;

    -- 10. Rental count per customer
SELECT customer_id,
    COUNT(rental_id) AS rental_count
FROM rental_tab
GROUP BY customer_id
ORDER BY rental_count DESC;

  -- 11. Average rental duration (in days)
SELECT AVG(DATEDIFF(return_date, rental_date)) AS avg_rental_days
FROM rental_tab;

   -- 12. Total revenue generated
SELECT SUM(amount) AS total_revenue
FROM payment;

   -- 13. Revenue generated by each staff member
SELECT staff_id,SUM(amount) AS sum_amount
FROM payment
GROUP BY staff_id
ORDER BY sum_amount DESC;

  -- 14. Revenue contribution by customer
SELECT 
    customer_id, SUM(amount) AS sum_amount
FROM payment
GROUP BY customer_id
ORDER BY sum_amount DESC;

  -- 15. Rental distribution by city
SELECT a.city_id, COUNT(*) AS rental_count
FROM rental_tab r
JOIN customer_tab c ON c.customer_id = r.customer_id
JOIN address_tab a ON a.address_id = c.address_id
GROUP BY a.city_id
ORDER BY rental_count DESC;

  -- 16. Revenue by film category
SELECT fc.category_id,
    SUM(p.amount) AS sum_amount
FROM payment p
JOIN rental_tab r ON p.rental_id = r.rental_id
JOIN inventory i ON i.inventory_id = r.inventory_id
JOIN film_category fc ON fc.film_id = i.film_id
GROUP BY fc.category_id
ORDER BY sum_amount DESC;